/**

  @file    serialize/common/osal_intser.c
  @brief   Serialize integers.
  @author  Pekka Lehtikoski
  @version 1.0
  @date    8.1.2020

  Pack and unpack integers for serialization.

  Copyright 2020 Pekka Lehtikoski. This file is part of the eosal and shall only be used,
  modified, and distributed under the terms of the project licensing. By continuing to use, modify,
  or distribute this file you indicate that you have read the license and understand and accept
  it fully.

****************************************************************************************************
*/
#include "eosalx.h"
#if OSAL_SERIALIZE_SUPPORT


/**
****************************************************************************************************

  @brief Convert integer to packed serial format.
  @anchor osal_intser_writer

  The osal_intser_writer() function pack integer x to serialization format. Serialization 
  format is packed by integer value size. Packed format is type independent, number of 
  generated bytes depends on value, not data type.

  First byte NNNNSxxx:
  - NNNM number of follower bytes.
  - S sign
  - xxx Least significant 3 data bits.

  @param  buf Buffer where to store the serialized integer, minimum OSAL_INTSER_BUF_SZ (10)
          charactters.
  @param  x Integer to serialize.
  @return Number of bytes stored in buf. 

****************************************************************************************************
*/
os_int osal_intser_writer(
	os_char *buf,
	os_long x)
{
    os_int n;
    os_char *p;

    if (x < 0x08)
	{
		if (x >= 0)
		{
			*buf = (os_char)x;
			return 1;
        }

        x = -x;
        if (x < 0x08)
        {
            *buf = (os_char)x | 0x08;
            return 1;
        }

        *buf = (os_char)(x & 0xF) | 0x08;
	}
	else
	{
        *buf = (os_char)x & 0x7;
	}

	p = buf;
    x >>= 3;

	do
	{
		*(++p) = (os_char)x;
		x >>= 8;
	}
    while (x);

	n = (os_int)(p - buf);
    *buf |= ((os_char)n << 4);

    return n + 1;
}


/**
****************************************************************************************************

  @brief Get integer from packed serial format.
  @anchor osal_intser_reader

  The osal_intser_reader() function converts serialzed integer to C integer x.

  @param  buf Bufffer from which to parse integer.
  @param  x Pointer where store the C integer.
  @return Number of bytes parsed from buf. 

****************************************************************************************************
*/
os_int osal_intser_reader(
    const os_char *buf,
	os_long *x)
{
    os_int shift;
    os_uchar c, count, *p;
    os_ulong y; /* signs are important here */

	c = *buf;
    if ((c & 0xF0) == 0)
	{
        *x = (c & 0x07);
        if (c & 0x08)
        {
            if (*x) { *x = -*x; }
            else
            {
                y = ~0;
                y >>= 1;
                *x = (os_long)(y ^ ~0);
            }
        }

        return 1;
	}

    y = c & 0x7;
    count = c >> 4;
    shift = 3;
    p = (os_uchar*)buf;
	while (count--)
	{
        y |= ((os_ulong)*(++p)) << shift;
		shift += 8;
	}

    if (c & 0x08) *x = -(os_long)y;
    else *x = (os_long)y;

    return (os_int)((os_char*)p - buf + 1);
}

#endif
