/**

  @file    stringx/common/osal_str_to_bin.c
  @brief   Convert string to binary MAC or IP address.
  @author  Pekka Lehtikoski
  @version 1.0
  @date    8.1.2020

  Copyright 2020 Pekka Lehtikoski. This file is part of the eosal and shall only be used, 
  modified, and distributed under the terms of the project licensing. By continuing to use, modify,
  or distribute this file you indicate that you have read the license and understand and accept 
  it fully.

****************************************************************************************************
*/
#include "eosalx.h"
#if OSAL_STRINGX_SUPPORT

/**
****************************************************************************************************

  @brief Convert binary IP address to string.
  @anchor osal_ip_to_str

  The osal_ip_to_str() converts binary IP address to string representation. This function can
  be used for both IPv4 and IPv6 addressess.

  Example outouts, IPv4 address "192.168.1.222" or IPv6 address
  "2001:0db8:85a3:0000:0000:8a2e:0370:7334".

  @param   str IP string generated by this function.
  @param   str_sz IP string buffer size. This should be OSAL_IPADDR_SZ bytes to allow
           enough space for IPv6 addresses.
  @param   ip Binary IP address to convert in netork byte order (more significant byte first).
  @param   ip_sz Value 4 bytes for IPv4 addressess or 16 for IPv6.
  @return  None.

****************************************************************************************************
*/
void osal_ip_to_str(
    os_char *str,
    os_memsz str_sz,
    const os_uchar *ip,
    os_memsz ip_sz)
{
    os_char nbuf[OSAL_NBUF_SZ];
    os_uint u;
    os_int i;

    osal_debug_assert(str);
    osal_debug_assert(ip);

    str[0] = '\0';
    switch (ip_sz)
    {
        case 16:
            for (i = 0; i < 8; i++)
            {
                u = ((os_uint)*(ip++)) << 8;
                u |= *(ip++);
                if (i) os_strncat(str, ":", str_sz);
                osal_int_to_str(nbuf, sizeof(nbuf), u);
                os_strncat(str, nbuf, str_sz);
            }
            break;

        case 4:
            for (i = 0; i < 4; i++)
            {
                if (i) os_strncat(str, ".", str_sz);
                osal_int_to_str(nbuf, sizeof(nbuf), ip[i]);
                os_strncat(str, nbuf, str_sz);
            }
            break;

        default:
            osal_debug_error("osal_ip_to_str: illegal ip_sz");
            break;
    }
}

#endif
