#!/usr/bin/env python3
# set_version.py 6.7.2020/pekka
# Change software version number (automatic date/time based versioning).
import time
import os.path

# Write a file only if content has changed
def write_file_only_if_changed(filepath, content):
    if (os.path.isfile(filepath)):
        hfile = open(filepath, "r")
        old_content = hfile.read()
        hfile.close()
        if (content == old_content):
            exit(None)

    hfile = open(filepath, "w")
    hfile.write(content)
    hfile.close()

def write_version_h():
    global target_path, version_date, version_time
    content  = '/* eosal_version.h is generated by set_version.py script, do not modify */\n'
    content += '#define OSAL_BUILD_DATE "' + version_date + '"\n'
    content += '#define OSAL_BUILD_TIME "' + version_time + '"\n'
    content += '#define OSAL_BUILD_DATETIME "' + version_date + '-' + version_time + '"\n'
    write_file_only_if_changed(target_path + "/eosal_version.h", content)

def write_version_txt():
    global target_path, version_date, version_time
    content = version_date + '-' + version_time
    write_file_only_if_changed(target_path + "/eosal_version.txt", content)

def set_version():
    global target_path, version_date, version_time
    target_path = '/coderoot/eosal'
    t = time.gmtime()
    version_date = time.strftime("%y%m%d", t)
    # XXXX is used as time because in some build environments change in "osal_version.h" triggets full rebuild. 
    # version_time = time.strftime("%H%M", t)
    version_time = "XXXX"
    write_version_h()
    write_version_txt()
    exit(None)

if __name__ == "__main__":
    # execute only if run as a script
    set_version()
    