# set_version.py 6.7.2020/pekka
# Change software version number (automatic date/time based versioning).
# from time import gmtime, strftime
import time

def write_version_h():
    global target_path, version_date, version_time
    hfile = open(target_path + "/eosal_version.h", "w")
    hfile.write('/* eosal_version.h is generated by set_version.py script, do not modify */\n')
    hfile.write('#define OSAL_BUILD_DATE "' + version_date + '"\n')
    hfile.write('#define OSAL_BUILD_TIME "' + version_time + '"\n')
    hfile.write('#define OSAL_BUILD_DATETIME "' + version_date + '-' + version_time + '"\n')
    hfile.close()

def write_version_txt():
    global target_path, version_date, version_time
    txtfile = open(target_path + "/eosal_version.txt", "w")
    txtfile.write(version_date + '-' + version_time)
    txtfile.close()


def set_version():
    global target_path, version_date, version_time
    target_path = '/coderoot/eosal'
    t = time.gmtime()
    version_date = time.strftime("%y%m%d", t)
    version_time = time.strftime("%H%M", t)
    write_version_h()
    write_version_txt()


if __name__ == "__main__":
    # execute only if run as a script
    set_version()
